services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"  
    volumes:
      
      - ./backend:/app
    env_file:
      - ./backend/.env 

  
  frontend:
    build: ./frontend 
    ports:
      - "5173:80"    
    volumes:
      
      - ./frontend/src:/app/src
