name: CI/CD - Build & Deploy Frontend and Backend

# This workflow runs automatically on any push to the "main" branch
on:
  push:
    branches: [ "main" ]

jobs:
  # --- JOB 1: DEPLOY FRONTEND TO VERCEL ---
  deploy-frontend:
    name: Deploy Frontend to Vercel
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ./frontend

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ./frontend

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ./frontend

  # --- JOB 2: DEPLOY BACKEND TO HUGGING FACE SPACES ---
  deploy-backend:
    name: Deploy Backend to Hugging Face
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Push to Hugging Face Space
        # This step pushes the contents of the 'backend' folder to your Space's main branch.
        # The HF_TOKEN is used for authentication.
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git subtree push --prefix backend https://hiabhinavvv:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/hiabhinavvv/vectoread-backend main