name: CI/CD - Build & Deploy Services

# This workflow runs automatically on any push to the "main" branch
on:
  push:
    branches: [ "main" ]

jobs:
  # --- JOB 1: CONTINUOUS INTEGRATION (Build & Push Docker Images) ---
  build-and-push-images:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/vectoread-backend:latest

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/vectoread-frontend:latest

# --- JOB 2: DEPLOY FRONTEND TO VERCEL (CD) ---
  deploy-frontend:
    name: Deploy Frontend to Vercel
    runs-on: ubuntu-latest
    needs: build-and-push-images

    # Add this env block to make the secrets available to all steps in this job
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      # The Vercel CLI will now automatically use the environment variables
      # to link to the correct project, so the 'pull' command is no longer needed.

      - name: Build Project Artifacts
        run: vercel build --prod
        working-directory: ./frontend

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod
        working-directory: ./frontend

  # --- JOB 3: DEPLOY BACKEND TO HUGGING FACE (CD) ---
  deploy-backend:
    name: Deploy Backend to Hugging Face
    runs-on: ubuntu-latest
    # This job will also only run if the 'build-and-push-images' job is successful
    needs: build-and-push-images
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git subtree push --prefix backend https://${{ secrets.HF_USERNAME }}:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/${{ secrets.HF_USERNAME }}/${{ secrets.HF_SPACE_NAME }} main