# Name for your GitHub Actions workflow
name: CI/CD - Build, Push, and Deploy

# This workflow runs automatically on any push event to the "main" branch
on:
  push:
    branches: [ "main" ]

jobs:
  # --- JOB 1: CONTINUOUS INTEGRATION (Build & Push Docker Images) ---
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checks out your repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Log in to Docker Hub using secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 3: Build and push the Backend image
      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile # Corrected parameter name
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/vectoread-backend:latest

      # Step 4: Build and push the Frontend image
      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile # Corrected parameter name
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/vectoread-frontend:latest

  # --- JOB 2: CONTINUOUS DEPLOYMENT (Deploy Backend to Hugging Face) ---
  deploy-backend:
    name: Deploy Backend to Hugging Face
    # This job will only run if the 'build-and-push' job completes successfully
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Push to Hugging Face Space
        env:
          # This makes your HF_TOKEN secret available as an environment variable
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # This command pushes ONLY the 'backend' subdirectory to your Space.
          # The URL is constructed with your username and the HF_TOKEN for authentication.
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git subtree push --prefix backend https://hiabhinavvv:${HF_TOKEN}@huggingface.co/spaces/hiabhinavvv/vectoread-backend main