name: CI/CD - Deploy Frontend and Backend

on:
  push:
    branches: [ "main" ]

jobs:
  # --- JOB 1: DEPLOY FRONTEND TO VERCEL ---
  deploy-frontend:
    name: Deploy Frontend to Vercel
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Pull Vercel Project Settings
        # This is the most critical step for linking the project.
        # It uses your secrets to download the project configuration.
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        # We run this command inside the frontend directory.
        working-directory: ./frontend

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ./frontend

      - name: Deploy Project to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ./frontend

  # --- JOB 2: DEPLOY BACKEND TO HUGGING FACE ---
  deploy-backend:
    name: Deploy Backend to Hugging Face
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          
          # This command now includes the --force flag.
          # It will overwrite the history on the Hugging Face Space, ensuring a clean deployment.
          git subtree push --prefix backend https://${{ secrets.HF_USERNAME }}:${HF_TOKEN}@huggingface.co/spaces/${{ secrets.HF_USERNAME }}/${{ secrets.HF_SPACE_NAME }} main --force