name: CI/CD - Build & Deploy Services

# This workflow runs automatically on any push to the "main" branch
on:
  push:
    branches: [ "main" ]

jobs:
  # --- JOB 1: CONTINUOUS INTEGRATION (Build & Push Docker Images) ---
  build-and-push-images:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/vectoread-backend:latest

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/vectoread-frontend:latest

  # --- JOB 2: DEPLOY FRONTEND TO VERCEL (CD) ---
  deploy-frontend:
    name: Deploy Frontend to Vercel
    runs-on: ubuntu-latest
    # This is the fix: This job now correctly depends on the build job above.
    needs: build-and-push-images

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Pull Vercel Project Settings
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ./frontend

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ./frontend

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ./frontend

  # --- JOB 3: DEPLOY BACKEND TO HUGGING FACE (CD) ---
  deploy-backend:
    name: Deploy Backend to Hugging Face
    runs-on: ubuntu-latest
    # This is the fix: This job also correctly depends on the build job.
    needs: build-and-push-images
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # We need the full git history for the subtree push command to work
          fetch-depth: 0

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          
          # Step 1: Create a temporary branch from the 'backend' subdirectory
          git subtree split --prefix backend -b temp-backend-branch
          
          # Step 2: Force push that temporary branch to the 'main' branch on Hugging Face
          git push --force https://${{ secrets.HF_USERNAME }}:${HF_TOKEN}@huggingface.co/spaces/${{ secrets.HF_USERNAME }}/${{ secrets.HF_SPACE_NAME }} temp-backend-branch:main
